language: scala

scala:
- 2.12.7

jdk:
- oraclejdk8

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install

env:
  global:
    JSENV=node

script:


deploy:
  provider: script
  script:
  - /bin/bash "$TRAVIS_BUILD_DIR/.travis.credentials.sh" && sbt ++$TRAVIS_SCALA_VERSION publish
  on:
    tags: true

env:
  global:
  # travis encrypt BINTRAY_USER=xxx
  - secure: "vbsCAhYFhBkf2Dr1LzAtOU+yPrJHyznppy0/LYBE6PbDnGHDblyruF5ntThJHWesqLJRb9eqMpUEd2Wbpsph1qC4VO2Z1hzAtoDvFSNNlt/zmrbS7G8CHjb7qSBVprVHEwhcMMGOMZcgUlBs4ISo6OOWuDrkwr3++hOum1nRRcPwENBQSY4mzTW5sybRYIKHUJz9QF3TOCxvcwXGSmZmxtE1Q6CSW6vkWg+YprTcUJj6/ZfSK+t3uBgRwmDikXcPavhVrMY5h++d3XyNSfYh3+h7xozr8gTA4AtbDGw9t7Vr76LH+qWqEI4h2MKn6OxmNOCX+igyg8ktmI4cgGGJ2Tpb+eOpXlZCS3VLEhyhmDTDkoofsgrBzWF9aUrRNLlI1/XsWM+t5tPeY1uChaH++i4gDgX188EhDBiYSAJewM6WPI7vYoqJr1adOC3Xk6IJ4bnM9xzuT7Sv13tSHefmjpnMfsxumpbmTJaznOfCtV4mhsiZ5K2fqFw5zzhiIqa0Opv3Gv5TVTjuWeMbOJYnpEElNLQuvxNgFvwzTumgezx0LcpNaH5KO7oNxp5JA4EbRuk+EO014QNPaI7CZe1rHkCvo34IMxYzuJ6W28PpyIOZcki/CzhbP5QwS1HQV54EyKmXeFNA5+JvK93NKzISaH+TXZp69zgZ7VaElg6tPiQ="
  # travis encrypt BINTRAY_PASSWORD=xxx
  - secure: "MypChaNc+29puCY0UWCgjZW8HO3ifjJyHWuKSgu/kaIUNrC6HEtP+GPYfzTJCTtnIVGKIa26EcDUbb93D1Gx7O9z/mXDONOZ8azohC+2uZalrxV2sWfpmIRA/XfPrghAWgJbjoD07l4yNoMce6CC4PwX9E3rjeD3c4kU/EuTuGL8yuR94A7ZsmEecILL4zvgcyUohkoFIHM4j0LKTQeHhagkUoQa/MW26lLWRauN8zfQyGTa+az71IV+q1Ld7BAGUuJf2lMV+p7tB3oIdaCgW6TQP5vrnV2OjKnyCQhxvZjnqmCTDVB3d4aWXVWq0SCBIhwog8Xa+qrTIUviq8M+tXs2SvTjegRmlS534Ee626gXrrUFda/CNMNkb3M+hTrO+wApt/mVNf0ppOUyBeySCoK2TgHq+tI+wxuxGtsNx7mxFlY9r9xYxxgsiy6BMwhqCHZ5UCs8VmlkUnEsRGhoPO1GrZyhp7oN3ZTQlzW88hza5rX87+tLiu91pqtCPKkwH+5LfEw0Gmd6e01eJ02j15XRBvZxuyK7hQo1NqPUvVGWcUtClVWfeq14G1ZVUgXcNek/QFsUV+Qr4ibHox/5jga2XsZt5A4rfFvvJluLhPQiwNfz+bzPeXqYksd21hTWnQIs7f6KUPfNzOThq+tVw0rt2jfvPB1r3C0Ru/6zmOY="


